### PR TITLE
Add EDA for input data set #125

### PR DESCRIPTION
**Pull request by shahules786**
Added EDA for the input data set
Results stored in Automl/EDA/Readme.md

### CODE REVIEW

**Comment by pplonski** [comment]
@shahules786 thank you for the contribution! Great job! :+1: 

My comments below:
1. Please use `black` for formatting.
2. EDA should work even if `y_train` is missing. For example, EDA for test data with no target available. Can you add a test for that?
3. I think `compute` in `EDA` should be static. Not need to store X, y in the `EDA` object. And the call from `AutoML` class should be static as well (it doesn't depend on AutoML parameters). 

Maybe keep static `compute` in `EDA` and call it for `fit` data in `AutoML` if `explain_level == 2` ?
  
4. Not sure, if we need information about the `ml_task`, I think we can just guess what kind to target it is and plot the distribution?
5. Can we add `mean` and `std` for continuous features?
6. Would love to see some examples and maybe little explanations how to use ins in `docs` directory (just add `automatic_eda.md` file in `docs` and explain with examples how it can be used)

**Comment by shahules786** [comment]
@pplonski Thanks for your review, I have some doubts
1.sorry, didn't get that..can you explain?
2. yes, Will do.
3 I can make  `compute`  in  `EDA`  static, the `eda` method of `automl` class should be static too? So how to identify the `results_path`?

**Comment by pplonski** [comment]
Hey @shahules786! Regarding questions:
3. You dont need `eda` method in `AutoML` class. The `eda` will be only called on new data in `fit` method in `AutoML` when `explain_level==2`. What do you think?
5. You are right. I missed that.

**Comment by shahules786** [comment]
@pplonski Ok,got it. Will do the necessary changes.

**Comment by shahules786** [comment]
@pplonski Done. Can you review it?
I will add the examples in this issue https://github.com/mljar/mljar-supervised/issues/146
Planning to add more detailed examples displaying more functionalities.

**Comment by pplonski** [comment]
Thank you! Looks good :)  Please fix the tests and I can merge it.

**Review by pplonski — APPROVED** [review]

**Pull request merged**
