### PR TITLE
Raising error for object input type & corresponding unit test

### PR DESCRIPTION
**Pull request by abtheo**
Fix for #147 

The issue is a lack of handling for the `object` type:

**Minimal Reproduction Example**

```
obj_array = np.array([1, 2, "A"], dtype=object) #<---
y = pd.DataFrame(obj_array)
X = y.copy()

a = AutoML(total_time=30,tuning_mode="Normal")

a.fit(X, y)
```

I like what you were doing with the Categorical-As-Text type parsing, so I attempted to handle this by casting the object values into strings... do not recommend. Objects cause a ton of problems downstream, it'd take a lot of work to fully integrate them into the application.

Instead, I've handled this by doing an early check on y, to raise an Exception if the consumer passes object types into the `fit()` function.

### CODE REVIEW

**Comment by pplonski** [comment]
Hey @abtheo! 

1. Please push changes directly to the `master` branch.
2. The type `object` is when there is a categorical feature. The `AutoML` should work with it, even in target values (for example look at Adult Income dataset, the target there are "<=50k", ">50k" and `AutoML` works with it.
3. Can we debug deeper this issue to check in which exact place there is an error?

**Review by pplonski — CHANGES_REQUESTED** [review]
We need to think about other way to fix it.  Please take a look that there are 14 errors in the tests.

**Comment by pplonski** [comment]
Too many changes - sorry I don't understand what's going on...

1. `AutoML` works with `object` dtype without these changes. The column with `object` dtype is treated as categorical or as a text.
2. There are errors in tests in Travis.

**Comment by pplonski** [comment]
@abtheo can we split this into smaller problems? with examples which break the `AutoML` and test cases

**Comment by abtheo** [comment]
Still a work in progress, sorry! I'm having a very difficult time running unit tests, seemingly because I'm running on Windows. 

I'll happily split up the work into separate PRs as soon as I can get all the tests passing 🙂

**Pull request closed without merging**
